apiVersion: apps/v1
kind: Deployment
metadata:
  name: scc2324-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scc2324-app
  template:
    metadata:
      labels:
        app: scc2324-app
    spec:
      nodeSelector:
          "kubernetes.io/os": linux
      containers:
      - name: scc2324-app
        image: rgoncalo/scc2324-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1024M
        env:
          - name: COSMOSDB_KEY
            value: "jZq4w7g3u5Ean3pnSi31gKBittRpZ99K9Kjxue2ZQkslN27yhFvngbqYdVNfHOpNuKivk4wlQGRJACDbUi6Nyw=="
          - name: COSMOSDB_URL
            value: "https://scc2459895.documents.azure.com:443/"
          - name: COSMOSDB_DATABASE
            value: "scc24db59895"
          - name: AzureCosmosDBConnection
            value: "AccountEndpoint=https://scc2459895.documents.azure.com:443/;AccountKey=jZq4w7g3u5Ean3pnSi31gKBittRpZ99K9Kjxue2ZQkslN27yhFvngbqYdVNfHOpNuKivk4wlQGRJACDbUi6Nyw=="
          - name: REDIS_URL
            value: "redis"
          - name: REDIS_PORT
            value: "6379"
          - name: REGION_NAME
            value: "westeurope"
          - name: REDIS_TIMEOUT
            value: "10000"
          - name: VOLUME_PATH
            value: "/mnt/vol"
        volumeMounts:
          - mountPath: "/mnt/vol"
            name: mediavolume
      volumes:
        - name: mediavolume
          persistentVolumeClaim:
            claimName: azure-managed-disk
---
apiVersion: v1
kind: Service
metadata:
  name: scc2324-app
spec:
  selector:
    app: scc2324-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

